#!/bin/bash

# CivicConnect Deployment Helper Script
echo "🚀 CivicConnect Deployment Helper"
echo "=================================="
echo ""

echo "This script will help you deploy your CivicConnect application."
echo "Choose your deployment option:"
echo ""
echo "1. Vercel (Frontend) + Railway (Backend) - RECOMMENDED"
echo "2. Render (All-in-One) - EASIEST"
echo "3. Netlify (Frontend) + Railway (Backend)"
echo "4. Show deployment guide"
echo ""

read -p "Enter your choice (1-4): " choice

case $choice in
    1)
        echo ""
        echo "🎯 Deploying to Vercel + Railway"
        echo "================================"
        echo ""
        echo "Step 1: Deploy Frontend to Vercel"
        echo "1. Go to https://vercel.com"
        echo "2. Sign up with GitHub"
        echo "3. Click 'New Project'"
        echo "4. Import your GitHub repository"
        echo "5. Set Framework: Create React App"
        echo "6. Set Build Command: npm run build"
        echo "7. Set Output Directory: build"
        echo "8. Click Deploy"
        echo ""
        echo "Step 2: Deploy Backend to Railway"
        echo "1. Go to https://railway.app"
        echo "2. Sign up with GitHub"
        echo "3. Click 'Deploy from GitHub repo'"
        echo "4. Select your repository"
        echo "5. Add environment variables (see below)"
        echo "6. Click Deploy"
        echo ""
        echo "Required Environment Variables for Backend:"
        echo "NODE_ENV=production"
        echo "PORT=5001"
        echo "MONGODB_URI=mongodb+srv://mahantigunavardhan:Gunavardhanmongo@cluster0.vkfwu.mongodb.net/civicconnect?retryWrites=true&w=majority&appName=Cluster0"
        echo "JWT_SECRET=your-super-secure-jwt-secret-key"
        echo "CLOUDINARY_CLOUD_NAME=your-cloudinary-name"
        echo "CLOUDINARY_API_KEY=your-cloudinary-key"
        echo "CLOUDINARY_API_SECRET=your-cloudinary-secret"
        echo "CORS_ORIGIN=https://your-vercel-app.vercel.app"
        echo ""
        echo "Frontend Environment Variable:"
        echo "REACT_APP_API_BASE=https://your-railway-app.railway.app/api"
        ;;
    2)
        echo ""
        echo "🎯 Deploying to Render (All-in-One)"
        echo "==================================="
        echo ""
        echo "Step 1: Deploy Backend to Render"
        echo "1. Go to https://render.com"
        echo "2. Sign up with GitHub"
        echo "3. Click 'New Web Service'"
        echo "4. Connect your GitHub repository"
        echo "5. Set Root Directory: backend"
        echo "6. Set Build Command: npm install"
        echo "7. Set Start Command: npm start"
        echo "8. Add environment variables (see below)"
        echo "9. Click Deploy"
        echo ""
        echo "Step 2: Deploy Frontend to Render"
        echo "1. Click 'New Static Site'"
        echo "2. Connect your GitHub repository"
        echo "3. Set Root Directory: frontend"
        echo "4. Set Build Command: npm install && npm run build"
        echo "5. Set Publish Directory: build"
        echo "6. Add environment variable:"
        echo "   REACT_APP_API_BASE=https://your-backend-service.onrender.com/api"
        echo "7. Click Deploy"
        echo ""
        echo "Required Environment Variables for Backend:"
        echo "NODE_ENV=production"
        echo "PORT=5001"
        echo "MONGODB_URI=mongodb+srv://mahantigunavardhan:Gunavardhanmongo@cluster0.vkfwu.mongodb.net/civicconnect?retryWrites=true&w=majority&appName=Cluster0"
        echo "JWT_SECRET=your-super-secure-jwt-secret-key"
        echo "CLOUDINARY_CLOUD_NAME=your-cloudinary-name"
        echo "CLOUDINARY_API_KEY=your-cloudinary-key"
        echo "CLOUDINARY_API_SECRET=your-cloudinary-secret"
        echo "CORS_ORIGIN=https://your-frontend-site.onrender.com"
        ;;
    3)
        echo ""
        echo "🎯 Deploying to Netlify + Railway"
        echo "================================="
        echo ""
        echo "Step 1: Deploy Frontend to Netlify"
        echo "1. Go to https://netlify.com"
        echo "2. Sign up with GitHub"
        echo "3. Click 'New site from Git'"
        echo "4. Connect your GitHub repository"
        echo "5. Set Build Command: npm run build"
        echo "6. Set Publish Directory: build"
        echo "7. Add environment variable:"
        echo "   REACT_APP_API_BASE=https://your-railway-app.railway.app/api"
        echo "8. Click Deploy"
        echo ""
        echo "Step 2: Deploy Backend to Railway (same as option 1)"
        ;;
    4)
        echo ""
        echo "📖 Opening deployment guide..."
        if command -v open &> /dev/null; then
            open DEPLOYMENT-SIMPLE.md
        else
            echo "Please open DEPLOYMENT-SIMPLE.md file to read the detailed guide."
        fi
        ;;
    *)
        echo "Invalid choice. Please run the script again and choose 1-4."
        ;;
esac

echo ""
echo "🎉 After deployment, your CivicConnect app will be live!"
echo "You can share the URL with users worldwide."
echo ""
echo "Need help? Check the DEPLOYMENT-SIMPLE.md file for detailed instructions."
